spring:
  application:
    name: helix-crm
  profiles:
    active: ${ACTIVE_SPRING_PROFILE:dev}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8081

logging:
  level:
    org.springframework.modulith: DEBUG

helix:
  company:
    name: Helix GPO
    legal-name: Helix GPO UG (haftungsbeschränkt) & Co. KG
    vat-id: ${HELIX_VAT_ID}
    address:
      street: Erftstraße
      house-number: "50"
      postal-code: "41460"
      city: Neuss
      country-code: DE
    email: helix.gpo@gmail.com
    iban: ${HELIX_IBAN}
    bic: ${HELIX_BIC}
  security:
    public-ip-allowlist: ${PUBLIC_IP_ALLOWLIST}
    cognito:
      client-id: ${COGNITO_CLIENT_ID}
